baseURL: https://arnoldocursos.com.br
DefaultContentLanguage: pt-br

languages:
  en:
    menu:
      header:
      - Name: about
        URL: '#sobre'
      - Name: courses
        URL: '#cursos'
      - Name: contact
        URL: '#contato'
    params:
      title: HAHAHAHA
  pt-br:
    menu:
      header:
      - Name: sobre
        URL: '#sobre'
      - Name: cursos
        URL: '#cursos'
      - Name: contato
        URL: '#contato'
    params:
      title: KKKKKK
  es:
    menu:
      header:
      - Name: about
        URL: '#sobre'
      - Name: courses
        URL: '#cursos'
      - Name: contact
        URL: '#contato'
    params:
      title: KKKKKK

params:
  sections:
    - _showcase
    # - about
    # - education
    # - experience
    # - client-and-work
    # - testimonial
    # - contact
    # - newsletter
  footer:
    copyright: © Raditian. All rights reserved.
    radity_logo:
      x: img/general/design-and-code-radity.png
      _2x: img/general/design-and-code-radity@2x.png
      alt: Design & Code - Radity
  plugins:
    css:
      - URL: css/animation.css
      - URL: css/main.css
      - URL: css/rad-icons.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
